# Generated by Django 2.0.7 on 2018-07-21 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hash', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='house',
            name='author_hash',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='housets',
            name='author_hash',
            field=models.UUIDField(null=True),
        ),
    ]
