# Generated by Django 2.0.7 on 2018-07-22 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_add_author_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='author_hash',
        ),
        migrations.RemoveField(
            model_name='housets',
            name='author_hash',
        ),
        migrations.AddField(
            model_name='author',
            name='truth',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='house',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rental.Author'),
        ),
        migrations.AddField(
            model_name='housets',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rental.Author'),
        ),
    ]
