# Generated by Django 2.0.7 on 2018-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerrequest', '0002_crawler_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestts',
            name='owner',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
