[tool.poetry]
name = "scrapy-tw-rental-house"
version = "2.3.0"
description = "Scrapy spider for TW Rental House"
readme = "README.md"
authors = ["ddio <ddio@ddio.io>"]
license = "MIT"
repository = "https://github.com/g0v/tw-rental-house-data/tree/master/scrapy-tw-rental-house"

[tool.poetry.dependencies]
python = "^3.10"
Scrapy = "^2.11.0"

[tool.poetry.scripts]
twrh = "scrapy_twrh.cli.main:main"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
